### PR TITLE
remove border, add right style for login link

### PR DESCRIPTION
**Pull request by madeira**

### CODE REVIEW

**Comment by esl4m** [comment]
@madeira 
I'm not sure about this one , can you send me a link or screenshot to the final output ?

**Comment by madeira** [comment]
@esl4m must be like this
https://www.evernote.com/l/AOuloLuVBIFEZraIlvAuespR0B9agRi8Xvs

**Comment by esl4m** [comment]
@madeira thank you for your comment , I removed the register button because now it appears above the login form .
Also in the last commits I added the text above the Noor logo and fixed it's size and display it on the right.
Can you please pull staging ?

**Comment by madeira** [comment]
@esl4m done

**Comment by esl4m** [comment]
@madeira thanks . Is it ok to merge this pull request now ?

**Comment by madeira** [comment]
@esl4m yes, we need to test this code in staging, without this pull I can't test code on staging. If you have some demo today, don't merge

**Comment by esl4m** [comment]
@madeira I will accept and please pull and test 👍

**Comment by esl4m** [comment]
@madeira it looks nice thanks 👍
We still have the responsive issue , can you please check ?

**Comment by madeira** [comment]
@esl4m yes, we will add responsive, when backend fix his problem

**Pull request merged**
