### PR TITLE
Naresh - js version upgrades

### PR DESCRIPTION
**Pull request by mack211777**

### CODE REVIEW

**Comment by esl4m** [comment]
@mack211777 Thank you ..
Please make this pull request on staging branch
https://github.com/ilearninteractive/ilearn-ginkgo/tree/staging

**Comment by mack211777** [comment]
@esl4m this is about merging it on staging branch. Shall I go ahead with this?

**Comment by esl4m** [comment]
ooh , yes .
Let's continue testing making sure everything is fine .
Then let's merge the request.

**Comment by mack211777** [comment]
@esl4m I traversed all of the static pages along with dashboard, courseware, discussion forum, account and instructor pages. Seems working fine on dev server.

**Pull request merged**
